name: CI PR
on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.3.1

      - name: Use Node.js
        uses: actions/setup-node@v3
        env:
          RUNNER_TEMP: '/tmp/'
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Run tests
        run: pnpm run coverage

      - name: Comment coverage
        if: always()
        uses: Tintef/nyc-reporter-action@0.2.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_COVERAGE_FOLDER: 'true'
