name: Publish latest version to npm
on:
  workflow_dispatch:
  push:
    tags:
      - v1.**

jobs:
  update-toc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js v16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install
        run: yarn
      - name: Build app
        run: yarn build

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.ACTION_PUBLISH_TOKEN }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
